export const SOCKET_EVENTS = {
    START_TEST: "START_TEST",
    ADD_ANSWER_RESPONSE: "ADD_CHOICE",
    ADD_VIDEO_CHUNK: "ADD_VIDEO_CHUNK",
    FINISH_TEST: "FINISH_TEST",
    ADD_FEEDBACK: "ADD_FEEDBACK",
    ADD_WARNING: "ADD_WARNING",
    ADD_QUESTION_STATUS: "ADD_QUESTION_STATUS",
    RUN_PROGRAM: "RUN_PROGRAM",
    SUBMIT_CODE: "SUBMIT_CODE",
}
